name: Huanan_market_samples
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - biopython=1.81
  - coverm=0.6.1
  - fastp=0.23.2
  - git-lfs
  - jupyterlab
  - mamba
  - markdown
  - mash=2.3
  - minimap2=2.24
  - openpyxl
  - pandas=1.5
  - pip
  - python=3.10
  - samtools=1.16
  - scipy
  - snakemake=7.25
  - pip:
    - altair==5.0.0rc1   
